export const STR = {
  title: "WASTELAND SURVIVOR",
  subtitle: "Top-down zombie survival",
  tapToStart: "TAP TO START",
  hintMove: "Drag left side to move",
  hintAim: "Drag right side to aim · auto-fires at nearest zombie",
  hintDash: "Tap DASH to dodge",
  wave: "WAVE",
  score: "SCORE",
  best: "BEST",
  coins: "COINS",
  waveClear: "WAVE CLEAR",
  chooseUpgrade: "CHOOSE AN UPGRADE",
  nextWaveIn: "NEXT WAVE IN",
  gameOver: "YOU DIED",
  finalScore: "FINAL SCORE",
  wavesSurvived: "WAVES SURVIVED",
  newBest: "NEW BEST SCORE!",
  restart: "TAP TO RESTART",
  paused: "PAUSED",
  resume: "RESUME",
  muteOn: "SOUND: ON",
  muteOff: "SOUND: OFF",
  dash: "DASH",
  upgradeHp: "Vitality\n+20 Max HP & full heal",
  upgradeDmg: "Sharp Rounds\n+20% Damage",
  upgradeFireRate: "Quick Trigger\n+15% Fire Rate",
  upgradeSpeed: "Adrenaline\n+10% Move Speed",
  upgradeDash: "Light Feet\n-20% Dash Cooldown",
  upgradePierce: "Armor Rounds\nBullets pierce +1 enemy",
  upgradeMagnet: "Scavenger\n+40% Pickup Radius",
  weaponPistol: "PISTOL",
  weaponSmg: "SMG",
  weaponShotgun: "SHOTGUN",
  bossIncoming: "BRUTE INCOMING",
};
